back/config/routes.rb
Rails.application.routes.draw do
  # get "/users/login/:user_name",to:'users#login'

  resources :payments
  resources :contributes
  resources :fines
  resources :loans
  resources :events
  resources :states
  resources :users
  resources :roles
  resources :tokens
  root 'tokens#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

back/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

back/app/models/contribute.rb
class Contribute < ApplicationRecord
  belongs_to :user
  belongs_to :event
  belongs_to :fine
end

back/app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :contribute
end

back/app/models/fine.rb
class Fine < ApplicationRecord
	has_many :contribute
end

back/app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  belongs_to :user
  belongs_to :state
end

back/app/models/member.rb
class Member < User
	include ActiveModel::Model
	
end

back/app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :loan
end

back/app/models/role.rb
class Role < ApplicationRecord
	has_many :user
	 validates :role,presence:{message:"el campo es requerido"}, length: { in: 1..15 , message: "debe tener entre 1 y 15 caracteres"}
		  validates :description,presence:{message:"el campo es requerido"}, length: { in: 1..300 , message: "debe tener entre 1 y 300 caracteres"}
end

back/app/models/state.rb
class State < ApplicationRecord
	has_many :loan
end

back/app/models/token.rb
class Token < ApplicationRecord
	before_create :assign_token
	
	#validaciones tokens
	validates :name, presence:true
	validates :number_of_requests,numericality: {greater_than_or_equal_to: 0}

	#crear el token random
	def assign_token
		self.token=SecureRandom.uuid
	end

	#verificar si existe un token en la base de datos
	def self.authenticate(auth_token)
		find_by(token:auth_token)
	end
end

back/app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  has_secure_password
  has_many :event
  has_many :loan
  has_many :contribute
  validates :name,presence:{message:"el campo es requerido"}, length: { in: 1..15 , message: "debe tener entre 1 y 15 caracteres"}
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message:"El formato del correo es invalido",on: :create },uniqueness: {case_sensitive: false ,message: "ya esta registrado"}
  validates :identity,presence:{message:"el campo es requerido"},length:{in:5..15,message:"debe tener entre 5 y 15 caracteres"},numericality:{only_integer:true, greater_than_or_equal_to: 0}
  validates :last_name,presence:{message:"el campo es requerido"}, length: { in: 1..20 , message: "debe tener entre 1 y 20 caracteres"}
  validates :user_name,presence:{message:"el campo es requerido"},uniqueness: {case_sensitive: false ,message: "El usuario ya esta registrado"},length:{in:4..15,message:"el user name debe tener entre 4 y 15 caracteres"}
  validates :password,presence:{message:"el campo es requerido"},length: { in: 8..20 , message: "debe tener entre 8 y 20 caracteres"}
  validates :password_confirmation,presence:{message:"el campo es requerido"},length: { in: 8..20 , message: "debe tener entre 8 y 20 caracteres"}
end

back/app/controllers/fines_controller.rb
class FinesController < ApplicationController
  before_action :set_fine, only: [:show, :edit, :update, :destroy]

  # GET /fines
  # GET /fines.json
  def index
    @fines = Fine.all
  end

  # GET /fines/1
  # GET /fines/1.json
  def show
  end

  # GET /fines/new
  def new
    @fine = Fine.new
  end

  # GET /fines/1/edit
  def edit
  end

  # POST /fines
  # POST /fines.json
  def create
    @fine = Fine.new(fine_params)

    respond_to do |format|
      if @fine.save
        format.html { redirect_to @fine, notice: 'Fine was successfully created.' }
        format.json { render :show, status: :created, location: @fine }
      else
        format.html { render :new }
        format.json { render json: @fine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fines/1
  # PATCH/PUT /fines/1.json
  def update
    respond_to do |format|
      if @fine.update(fine_params)
        format.html { redirect_to @fine, notice: 'Fine was successfully updated.' }
        format.json { render :show, status: :ok, location: @fine }
      else
        format.html { render :edit }
        format.json { render json: @fine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fines/1
  # DELETE /fines/1.json
  def destroy
    @fine.destroy
    respond_to do |format|
      format.html { redirect_to fines_url, notice: 'Fine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fine
      @fine = Fine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fine_params
      params.require(:fine).permit(:name, :description, :price)
    end
end

back/app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:user_id, :user_id, :amount_loan, :balance, :state_id)
    end
end

back/app/helpers/application_helper.rb
module ApplicationHelper
end

back/app/helpers/contributes_helper.rb
module ContributesHelper
end

back/app/helpers/events_helper.rb
module EventsHelper
end

back/app/helpers/fines_helper.rb
module FinesHelper
end

back/app/helpers/loans_helper.rb
module LoansHelper
end

back/app/helpers/payments_helper.rb
module PaymentsHelper
end

back/app/helpers/roles_helper.rb
module RolesHelper
end

back/app/helpers/states_helper.rb
module StatesHelper
end

back/app/helpers/tokens_helper.rb
module TokensHelper
end

back/app/helpers/users_helper.rb
module UsersHelper
end

back/app/views/fines/_form.html.erb
<%= form_for(fine) do |f| %>
  <% if fine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fine.errors.count, "error") %> prohibited this fine from being saved:</h2>

      <ul>
      <% fine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

back/app/views/fines/edit.html.erb
<h1>Editing Fine</h1>

<%= render 'form', fine: @fine %>

<%= link_to 'Show', @fine %> |
<%= link_to 'Back', fines_path %>

back/app/views/fines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fines.each do |fine| %>
      <tr>
        <td><%= fine.name %></td>
        <td><%= fine.description %></td>
        <td><%= fine.price %></td>
        <td><%= link_to 'Show', fine %></td>
        <td><%= link_to 'Edit', edit_fine_path(fine) %></td>
        <td><%= link_to 'Destroy', fine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fine', new_fine_path %>

back/app/views/fines/new.html.erb
<h1>New Fine</h1>

<%= render 'form', fine: @fine %>

<%= link_to 'Back', fines_path %>

back/app/views/fines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fine.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fine.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @fine.price %>
</p>

<%= link_to 'Edit', edit_fine_path(@fine) %> |
<%= link_to 'Back', fines_path %>

back/app/views/loans/_form.html.erb
<%= form_for(loan) do |f| %>
  <% if loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.collection_select :user_id,User.where({active:true}),:id,:name %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.collection_select :user_id,User.where({active:true,role_id:1}),:id,:name %>
  </div>

  <div class="field">
    <%= f.label :amount_loan %>
    <%= f.number_field :amount_loan %>
  </div>

  <div class="field">
    <%= f.label :balance %>
    <%= f.number_field :balance %>
  </div>

  <div class="field">
    <%= f.label :state_id %>
    <%= f.collection_select :state_id,State.all,:id,:state %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

back/app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

back/app/views/loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Loans</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Responsable</th>
      <th>Amount loan</th>
      <th>Balance</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.user.name %></td>
        <td><%= loan.user.name %></td>
        <td><%= loan.amount_loan %></td>
        <td><%= loan.balance %></td>
        <td><%= loan.state.state %></td>
        <td><%= link_to 'Show', loan %></td>
        <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
        <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loan', new_loan_path %>

back/app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Back', loans_path %>

back/app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @loan.user %>
</p>

<p>
  <strong>User:</strong>
  <%= @loan.user %>
</p>

<p>
  <strong>Amount loan:</strong>
  <%= @loan.amount_loan %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @loan.balance %>
</p>

<p>
  <strong>State:</strong>
  <%= @loan.state %>
</p>

<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', loans_path %>