back/config/routes.rb
Rails.application.routes.draw do
  # get "/users/login/:user_name",to:'users#login'

  resources :payments
  resources :contributes
  resources :fines
  resources :loans
  resources :events
  resources :states
  resources :users
  resources :roles
  resources :tokens
  root 'tokens#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

back/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

back/app/models/contribute.rb
class Contribute < ApplicationRecord
  belongs_to :user
  belongs_to :event
  belongs_to :fine
end

back/app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :contribute
end

back/app/models/fine.rb
class Fine < ApplicationRecord
	has_many :contribute
end

back/app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  belongs_to :user
  belongs_to :state
end

back/app/models/member.rb
class Member < User
	include ActiveModel::Model
	
end

back/app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :loan
end

back/app/models/role.rb
class Role < ApplicationRecord
	has_many :user
	 validates :role,presence:{message:"el campo es requerido"}, length: { in: 1..15 , message: "debe tener entre 1 y 15 caracteres"}
		  validates :description,presence:{message:"el campo es requerido"}, length: { in: 1..300 , message: "debe tener entre 1 y 300 caracteres"}
end

back/app/models/state.rb
class State < ApplicationRecord
	has_many :loan
end

back/app/models/token.rb
class Token < ApplicationRecord
	before_create :assign_token
	
	#validaciones tokens
	validates :name, presence:true
	validates :number_of_requests,numericality: {greater_than_or_equal_to: 0}

	#crear el token random
	def assign_token
		self.token=SecureRandom.uuid
	end

	#verificar si existe un token en la base de datos
	def self.authenticate(auth_token)
		find_by(token:auth_token)
	end
end

back/app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  has_secure_password
  has_many :event
  has_many :loan
  has_many :contribute
  validates :name,presence:{message:"el campo es requerido"}, length: { in: 1..15 , message: "debe tener entre 1 y 15 caracteres"}
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message:"El formato del correo es invalido",on: :create },uniqueness: {case_sensitive: false ,message: "ya esta registrado"}
  validates :identity,presence:{message:"el campo es requerido"},length:{in:5..15,message:"debe tener entre 5 y 15 caracteres"},numericality:{only_integer:true, greater_than_or_equal_to: 0}
  validates :last_name,presence:{message:"el campo es requerido"}, length: { in: 1..20 , message: "debe tener entre 1 y 20 caracteres"}
  validates :user_name,presence:{message:"el campo es requerido"},uniqueness: {case_sensitive: false ,message: "El usuario ya esta registrado"},length:{in:4..15,message:"el user name debe tener entre 4 y 15 caracteres"}
  validates :password,presence:{message:"el campo es requerido"},length: { in: 8..20 , message: "debe tener entre 8 y 20 caracteres"}
  validates :password_confirmation,presence:{message:"el campo es requerido"},length: { in: 8..20 , message: "debe tener entre 8 y 20 caracteres"}
end

back/app/controllers/fines_controller.rb
class FinesController < ApplicationController
  before_action :set_fine, only: [:show, :edit, :update, :destroy]

  # GET /fines
  # GET /fines.json
  def index
    @fines = Fine.all
  end

  # GET /fines/1
  # GET /fines/1.json
  def show
  end

  # GET /fines/new
  def new
    @fine = Fine.new
  end

  # GET /fines/1/edit
  def edit
  end

  # POST /fines
  # POST /fines.json
  def create
    @fine = Fine.new(fine_params)

    respond_to do |format|
      if @fine.save
        format.html { redirect_to @fine, notice: 'Fine was successfully created.' }
        format.json { render :show, status: :created, location: @fine }
      else
        format.html { render :new }
        format.json { render json: @fine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fines/1
  # PATCH/PUT /fines/1.json
  def update
    respond_to do |format|
      if @fine.update(fine_params)
        format.html { redirect_to @fine, notice: 'Fine was successfully updated.' }
        format.json { render :show, status: :ok, location: @fine }
      else
        format.html { render :edit }
        format.json { render json: @fine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fines/1
  # DELETE /fines/1.json
  def destroy
    @fine.destroy
    respond_to do |format|
      format.html { redirect_to fines_url, notice: 'Fine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fine
      @fine = Fine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fine_params
      params.require(:fine).permit(:name, :description, :price)
    end
end

back/app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:loan_id, :interest, :quota, :date)
    end
end

back/app/helpers/application_helper.rb
module ApplicationHelper
end

back/app/helpers/contributes_helper.rb
module ContributesHelper
end

back/app/helpers/events_helper.rb
module EventsHelper
end

back/app/helpers/fines_helper.rb
module FinesHelper
end

back/app/helpers/loans_helper.rb
module LoansHelper
end

back/app/helpers/payments_helper.rb
module PaymentsHelper
end

back/app/helpers/roles_helper.rb
module RolesHelper
end

back/app/helpers/states_helper.rb
module StatesHelper
end

back/app/helpers/tokens_helper.rb
module TokensHelper
end

back/app/helpers/users_helper.rb
module UsersHelper
end

back/app/views/payments/_form.html.erb
<%= form_for(payment) do |f| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :loan_id %>
    <%= f.text_field :loan_id %>
  </div>

  <div class="field">
    <%= f.label :interest %>
    <%= f.text_field :interest %>
  </div>

  <div class="field">
    <%= f.label :quota %>
    <%= f.number_field :quota %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

back/app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

back/app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Loan</th>
      <th>Interest</th>
      <th>Quota</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.loan %></td>
        <td><%= payment.interest %></td>
        <td><%= payment.quota %></td>
        <td><%= payment.date %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

back/app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

back/app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Loan:</strong>
  <%= @payment.loan %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @payment.interest %>
</p>

<p>
  <strong>Quota:</strong>
  <%= @payment.quota %>
</p>

<p>
  <strong>Date:</strong>
  <%= @payment.date %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>