back/config/routes.rb
Rails.application.routes.draw do
  # get "/users/login/:user_name",to:'users#login'

  resources :payments
  resources :contributes
  resources :fines
  resources :loans
  resources :events
  resources :states
  resources :users
  resources :roles
  resources :tokens
  root 'tokens#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

back/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

back/app/models/contribute.rb
class Contribute < ApplicationRecord
  belongs_to :user
  belongs_to :event
  belongs_to :fine
end

back/app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :contribute
end

back/app/models/fine.rb
class Fine < ApplicationRecord
	has_many :contribute
end

back/app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  belongs_to :user
  belongs_to :state
end

back/app/models/member.rb
class Member < User
	include ActiveModel::Model
	
end

back/app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :loan
end

back/app/models/role.rb
class Role < ApplicationRecord
	has_many :user
	 validates :role,presence:{message:"el campo es requerido"}, length: { in: 1..15 , message: "debe tener entre 1 y 15 caracteres"}
		  validates :description,presence:{message:"el campo es requerido"}, length: { in: 1..300 , message: "debe tener entre 1 y 300 caracteres"}
end

back/app/models/state.rb
class State < ApplicationRecord
	has_many :loan
end

back/app/models/token.rb
class Token < ApplicationRecord
	before_create :assign_token
	
	#validaciones tokens
	validates :name, presence:true
	validates :number_of_requests,numericality: {greater_than_or_equal_to: 0}

	#crear el token random
	def assign_token
		self.token=SecureRandom.uuid
	end

	#verificar si existe un token en la base de datos
	def self.authenticate(auth_token)
		find_by(token:auth_token)
	end
end

back/app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  has_secure_password
  has_many :event
  has_many :loan
  has_many :contribute
  validates :name,presence:{message:"el campo es requerido"}, length: { in: 1..15 , message: "debe tener entre 1 y 15 caracteres"}
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message:"El formato del correo es invalido",on: :create },uniqueness: {case_sensitive: false ,message: "ya esta registrado"}
  validates :identity,presence:{message:"el campo es requerido"},length:{in:5..15,message:"debe tener entre 5 y 15 caracteres"},numericality:{only_integer:true, greater_than_or_equal_to: 0}
  validates :last_name,presence:{message:"el campo es requerido"}, length: { in: 1..20 , message: "debe tener entre 1 y 20 caracteres"}
  validates :user_name,presence:{message:"el campo es requerido"},uniqueness: {case_sensitive: false ,message: "El usuario ya esta registrado"},length:{in:4..15,message:"el user name debe tener entre 4 y 15 caracteres"}
  validates :password,presence:{message:"el campo es requerido"},length: { in: 8..20 , message: "debe tener entre 8 y 20 caracteres"}
  validates :password_confirmation,presence:{message:"el campo es requerido"},length: { in: 8..20 , message: "debe tener entre 8 y 20 caracteres"}
end

back/app/helpers/application_helper.rb
module ApplicationHelper
end

back/app/helpers/events_helper.rb
module EventsHelper
end

back/app/helpers/fines_helper.rb
module FinesHelper
end

back/app/helpers/loans_helper.rb
module LoansHelper
end

back/app/helpers/payments_helper.rb
module PaymentsHelper
end

back/app/helpers/roles_helper.rb
module RolesHelper
end

back/app/helpers/states_helper.rb
module StatesHelper
end

back/app/helpers/tokens_helper.rb
module TokensHelper
end

back/app/helpers/users_helper.rb
module UsersHelper
end

back/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Back</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
    <div class="nav-wrapper">
      <%= link_to 'ClubMoney',root_path,class:'brand-logo' %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li>
        	<%= link_to 'Roles',roles_path %>
        </li>
        <li>
        	<%= link_to 'Usuarios',users_path %>
        </li>
        <li>
        	<%= link_to 'Estados',states_path %>
        </li>
        <li>
        	<%= link_to 'Multas',fines_path %>
        </li>
        <li>
        	<%= link_to 'Tokens',tokens_path %>
        </li>
        <li>
        	<%= link_to 'Abonos',payments_path %>
        </li>
         <li>
        	<%= link_to 'Eventos',events_path %>
        </li>
        <li>
        	<%= link_to 'Prestamos',loans_path %>
        </li>
        <li>
        	<%= link_to 'Aportes',contributes_path %>
        </li>
      </ul>
    </div>
  </nav>
    <%= yield %>
 <!--     <footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Contactos</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2016 WeDevJS
            <!-- <a class="grey-text text-lighten-4 right" href="#!">More Links</a> -->
            </div>
          </div>
        </footer> -->
  </body>
</html>