back/config/routes.rb
Rails.application.routes.draw do
  # get "/users/login/:user_name",to:'users#login'

  resources :payments
  resources :contributes
  resources :fines
  resources :loans
  resources :events
  resources :states
  resources :users
  resources :roles
  resources :tokens
  root 'tokens#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

back/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

back/app/models/contribute.rb
class Contribute < ApplicationRecord
  belongs_to :user
  belongs_to :event
  belongs_to :fine
end

back/app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :contribute
end

back/app/models/fine.rb
class Fine < ApplicationRecord
	has_many :contribute
end

back/app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  belongs_to :user
  belongs_to :state
end

back/app/models/member.rb
class Member < User
	include ActiveModel::Model
	
end

back/app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :loan
end

back/app/models/role.rb
class Role < ApplicationRecord
	has_many :user
	 validates :role,presence:{message:"el campo es requerido"}, length: { in: 1..15 , message: "debe tener entre 1 y 15 caracteres"}
		  validates :description,presence:{message:"el campo es requerido"}, length: { in: 1..300 , message: "debe tener entre 1 y 300 caracteres"}
end

back/app/models/state.rb
class State < ApplicationRecord
	has_many :loan
end

back/app/models/token.rb
class Token < ApplicationRecord
	before_create :assign_token
	
	#validaciones tokens
	validates :name, presence:true
	validates :number_of_requests,numericality: {greater_than_or_equal_to: 0}

	#crear el token random
	def assign_token
		self.token=SecureRandom.uuid
	end

	#verificar si existe un token en la base de datos
	def self.authenticate(auth_token)
		find_by(token:auth_token)
	end
end

back/app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  has_secure_password
  has_many :event
  has_many :loan
  has_many :contribute
  validates :name,presence:{message:"el campo es requerido"}, length: { in: 1..15 , message: "debe tener entre 1 y 15 caracteres"}
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message:"El formato del correo es invalido",on: :create },uniqueness: {case_sensitive: false ,message: "ya esta registrado"}
  validates :identity,presence:{message:"el campo es requerido"},length:{in:5..15,message:"debe tener entre 5 y 15 caracteres"},numericality:{only_integer:true, greater_than_or_equal_to: 0}
  validates :last_name,presence:{message:"el campo es requerido"}, length: { in: 1..20 , message: "debe tener entre 1 y 20 caracteres"}
  validates :user_name,presence:{message:"el campo es requerido"},uniqueness: {case_sensitive: false ,message: "El usuario ya esta registrado"},length:{in:4..15,message:"el user name debe tener entre 4 y 15 caracteres"}
  validates :password,presence:{message:"el campo es requerido"},length: { in: 8..20 , message: "debe tener entre 8 y 20 caracteres"}
  validates :password_confirmation,presence:{message:"el campo es requerido"},length: { in: 8..20 , message: "debe tener entre 8 y 20 caracteres"}
end

back/app/controllers/contributes_controller.rb
class ContributesController < ApplicationController
  before_action :set_contribute, only: [:show, :edit, :update, :destroy]

  # GET /contributes
  # GET /contributes.json
  def index
    @contributes = Contribute.all
  end

  # GET /contributes/1
  # GET /contributes/1.json
  def show
  end

  # GET /contributes/new
  def new
    @contribute = Contribute.new
  end

  # GET /contributes/1/edit
  def edit
  end

  # POST /contributes
  # POST /contributes.json
  def create
    @contribute = Contribute.new(contribute_params)

    respond_to do |format|
      if @contribute.save
        format.html { redirect_to @contribute, notice: 'Contribute was successfully created.' }
        format.json { render :show, status: :created, location: @contribute }
      else
        format.html { render :new }
        format.json { render json: @contribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contributes/1
  # PATCH/PUT /contributes/1.json
  def update
    respond_to do |format|
      if @contribute.update(contribute_params)
        format.html { redirect_to @contribute, notice: 'Contribute was successfully updated.' }
        format.json { render :show, status: :ok, location: @contribute }
      else
        format.html { render :edit }
        format.json { render json: @contribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributes/1
  # DELETE /contributes/1.json
  def destroy
    @contribute.destroy
    respond_to do |format|
      format.html { redirect_to contributes_url, notice: 'Contribute was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contribute
      @contribute = Contribute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contribute_params
      params.require(:contribute).permit(:user_id, :event_id, :quota, :snack, :fine_id, :debt)
    end
end

back/app/controllers/fines_controller.rb
class FinesController < ApplicationController
  before_action :set_fine, only: [:show, :edit, :update, :destroy]

  # GET /fines
  # GET /fines.json
  def index
    @fines = Fine.all
  end

  # GET /fines/1
  # GET /fines/1.json
  def show
  end

  # GET /fines/new
  def new
    @fine = Fine.new
  end

  # GET /fines/1/edit
  def edit
  end

  # POST /fines
  # POST /fines.json
  def create
    @fine = Fine.new(fine_params)

    respond_to do |format|
      if @fine.save
        format.html { redirect_to @fine, notice: 'Fine was successfully created.' }
        format.json { render :show, status: :created, location: @fine }
      else
        format.html { render :new }
        format.json { render json: @fine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fines/1
  # PATCH/PUT /fines/1.json
  def update
    respond_to do |format|
      if @fine.update(fine_params)
        format.html { redirect_to @fine, notice: 'Fine was successfully updated.' }
        format.json { render :show, status: :ok, location: @fine }
      else
        format.html { render :edit }
        format.json { render json: @fine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fines/1
  # DELETE /fines/1.json
  def destroy
    @fine.destroy
    respond_to do |format|
      format.html { redirect_to fines_url, notice: 'Fine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fine
      @fine = Fine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fine_params
      params.require(:fine).permit(:name, :description, :price)
    end
end

back/app/helpers/application_helper.rb
module ApplicationHelper
end

back/app/helpers/contributes_helper.rb
module ContributesHelper
end

back/app/helpers/events_helper.rb
module EventsHelper
end

back/app/helpers/fines_helper.rb
module FinesHelper
end

back/app/helpers/loans_helper.rb
module LoansHelper
end

back/app/helpers/payments_helper.rb
module PaymentsHelper
end

back/app/helpers/roles_helper.rb
module RolesHelper
end

back/app/helpers/states_helper.rb
module StatesHelper
end

back/app/helpers/tokens_helper.rb
module TokensHelper
end

back/app/helpers/users_helper.rb
module UsersHelper
end

back/app/views/contributes/_form.html.erb
<%= form_for(contribute) do |f| %>
  <% if contribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contribute.errors.count, "error") %> prohibited this contribute from being saved:</h2>

      <ul>
      <% contribute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :event_id %>
    <%= f.text_field :event_id %>
  </div>

  <div class="field">
    <%= f.label :quota %>
    <%= f.number_field :quota %>
  </div>

  <div class="field">
    <%= f.label :snack %>
    <%= f.number_field :snack %>
  </div>

  <div class="field">
    <%= f.label :fine_id %>
    <%= f.text_field :fine_id %>
  </div>

  <div class="field">
    <%= f.label :debt %>
    <%= f.number_field :debt %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

back/app/views/contributes/edit.html.erb
<h1>Editing Contribute</h1>

<%= render 'form', contribute: @contribute %>

<%= link_to 'Show', @contribute %> |
<%= link_to 'Back', contributes_path %>

back/app/views/contributes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contributes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Event</th>
      <th>Quota</th>
      <th>Snack</th>
      <th>Fine</th>
      <th>Debt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contributes.each do |contribute| %>
      <tr>
        <td><%= contribute.user.name + " "+ contribute.user.last_name %></td>
        <td><%= contribute.event.date %></td>
        <td><%= contribute.quota %></td>
        <td><%= contribute.snack %></td>
        <td><%= contribute.fine.name %></td>
        <td><%= contribute.debt %></td>
        <td><%= link_to 'Show', contribute %></td>
        <td><%= link_to 'Edit', edit_contribute_path(contribute) %></td>
        <td><%= link_to 'Destroy', contribute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contribute', new_contribute_path %>

back/app/views/contributes/new.html.erb
<h1>New Contribute</h1>

<%= render 'form', contribute: @contribute %>

<%= link_to 'Back', contributes_path %>

back/app/views/contributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @contribute.user %>
</p>

<p>
  <strong>Event:</strong>
  <%= @contribute.event %>
</p>

<p>
  <strong>Quota:</strong>
  <%= @contribute.quota %>
</p>

<p>
  <strong>Snack:</strong>
  <%= @contribute.snack %>
</p>

<p>
  <strong>Fine:</strong>
  <%= @contribute.fine %>
</p>

<p>
  <strong>Debt:</strong>
  <%= @contribute.debt %>
</p>

<%= link_to 'Edit', edit_contribute_path(@contribute) %> |
<%= link_to 'Back', contributes_path %>